alias barley='brew update && brew upgrade && brew linkapps && brew cleanup && brew prune && brew doctor'
alias jc='jcheck.plx -f'
alias joe='vim'
alias pc='pcheck.plx -f'
alias ps='colourify ps'
alias rm='rm -i'
